version: 2
updates:
  #For maven dependencies
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: monthly
      time: "07:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 2

  #For GHA dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
