# Conditional alerts: Will run on successful completion of ["Report", "Docker Image"] workflows
name: Alert

on:
  workflow_run:
    workflows: ["Report", "Docker Image"]
    branches: [master]
    types: [completed]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggered workflows passed'
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
             "text": "CI (Completed)",
              "attachments": [
                {
                  "pretext": "CI Passed",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Passed"
                    }
                  ]
                }
              ]
            }

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggered workflows failed'
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
             "text": "CI (Failed)",
              "attachments": [
                {
                  "pretext": "CI Failed",
                  "color": "e32803",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
