name: Docker Image

on:
  push:
    branches: ["master"]

  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: heyrmi

jobs:
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |-
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/apitestingframework:latest

      - name: Image Info
        run: |
          echo ${{ steps.docker_build.outputs.imageid }} 
          echo ${{ steps.docker_build.outputs.digest }}

      - name: Slack Alert
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "Latest Docker Image: https://hub.docker.com/repository/docker/heyrmi/apitestingframework"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
