name: Build Docker Image and deploy to Docker Hub

on:
  push:
    branches: ["master"]

  workflow_dispatch:

env:
  # DockerHub
  DOCKER_HUB_USERNAME: heyrmi


jobs:
  DockerPublish:
    runs-on: ubuntu-latest
    steps:
      #Slack Notification at start
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          #TODO: change the text
          text: "Docker image creation ongoing... :eyes:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_USERNAME }}/apitestingframework

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        #Slack Notification after deployment
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ":white_check_mark: pushed heyrmi/API-Testing-Framework to docker hub: https://hub.docker.com/repository/docker/heyrmi/apitestingframework"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

