name: Build Docker Image and deploy to Docker Hub

on:
  push:
    branches: [experimental-dev]

  workflow_dispatch:

env:
  # DockerHub
  DOCKER_HUB_USERNAME: heyrmi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          #TODO: change the text
          text: "Docker image creation ongoing... :eyes:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build Number
        id: build-number
        run: echo "name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Maven Clean Package
        continue-on-error: true
        run: mvn --no-transfer-progress clean package

      - name: Push to Dockerhub
        #check for maven-wrapper availablity in the Java installed
        #feasibility for some other tool other than JIB for pusing it to DockerHub
        run: |
          mvn -e -X -P jib-push-to-dockerhub \
          -D app.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ":white_check_mark: pushed heyrmi/API-Testing-Framework:${{steps.build-number.outputs.BUILD_NUMBER}} to docker hub... https://hub.docker.com/repository/docker/heyrmi/apitestingframework"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
