# Test for pull-requests to check if existing code is breaking due raised pull-request.
name: PR Test

on:
  pull_request:
    branches:
      - master

env:
  ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}

jobs:
  test:
    name: PR Test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: API Test
        # Have done this because one test set to fail deliberately for report (ideally we should remove this).
        continue-on-error: true
        run: mvn clean test --no-transfer-progress

      - name: Gatling Test
        run: mvn clean gatling:test --no-transfer-progress
