# Will deploy latest execution report, after running tests.
name: Tests

on:
  push:
    branches: ["master"]

env:
  ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}

jobs:
  rest-assured-test:
    name: REST Assured Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Maven Test
        # Have done this because one test set to fail deliberately for report (ideally we should remove this).
        continue-on-error: true
        run: mvn clean test --no-transfer-progress

      - name: Deploy Extent Report
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./Reports

      - name: Slack Alert
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "Latest Report Link :arrow_right: https://heyrmi.github.io/API-Testing-Framework/"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  gatling-test:
    name: Gatling Tests
    needs: [rest-assured-test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Maven Test
        run: mvn clean gatling:test --no-transfer-progress

      - name: Upload Gatling Reports
        uses: actions/upload-artifact@v3
        with:
          name: Gatling-Reports
          path: ./gatling-reports
